export const drivers = [
  { name: 'verstappen',  team: 'redbull' },
  { name: 'tsunoda',     team: 'redbull' },
  { name: 'leclerc',     team: 'ferrari' },
  { name: 'hamilton',    team: 'ferrari' },
  { name: 'norris',      team: 'mclaren' },
  { name: 'piastri',     team: 'mclaren' },
  { name: 'russell',     team: 'mercedes' },
  { name: 'antonelli',   team: 'mercedes' },
  { name: 'albon',       team: 'williams' },
  { name: 'sainz',       team: 'williams' },
  { name: 'lawson',      team: 'racingbulls' },
  { name: 'hadjar',      team: 'racingbulls' },
  { name: 'gasly',       team: 'alpine' },
  { name: 'colapinto',   team: 'alpine' },
  { name: 'ocon',        team: 'haas' },
  { name: 'bearman',     team: 'haas' },
  { name: 'alonso',      team: 'astonmartin' },
  { name: 'stroll',      team: 'astonmartin' },
  { name: 'hülkenberg',  team: 'sauber' },
  { name: 'bortoleto',   team: 'sauber' },
];
